baseURL = "https://www.alecburton.co.uk/"
languageCode = "en-us"
title = "Alec Burton's Blog"
disqusShortname = "alecburton"

theme = "jeffprod"

googleAnalytics = "UA-139657686-1"

[permalinks]
    post = "/:year/:filename"

[params]
  description = "A blog on programming and coaching."
  images = ["img/mull2.JPG"]
  title = "Alec Burton's Blog"

[taxonomies]
    tag = "tags"
    archive = "archives"
